region: ap-south-1
min_cpu: 8
max_cpu: 16
include_burstable: true

# Optional: use these instance types directly in fetch_by_machine_type.py
preferred_instance_types:
  - t3a.large
  - m6i.large
  - c5.large
  - t3a.xlarge
  - m6i.xlarge
  - c5.xlarge
  - t3a.2xlarge
  - m6i.2xlarge
  - c5.2xlarge
  - t3a.medium
  - m6i.4xlarge
  - c5.4xlarge
  - t3a.small
  - m6i.8xlarge
  - c5.9xlarge
  - t3a.nano
  - m6i.12xlarge
  - c5.12xlarge
  - t3a.micro
  - m6i.16xlarge
  - c5.18xlarge
  - m6i.24xlarge
  - c5.24xlarge
  - m6i.32xlarge
  - c5.metal
  - m6i.metal
  - c5d.large
  - c5d.xlarge
  - c5d.2xlarge
  - c5d.4xlarge
  - c5d.9xlarge
  - c5d.12xlarge
  - c5d.18xlarge
  - c5d.24xlarge
  - c5d.metal
  - m6id.large
  - m6id.xlarge
  - m6id.2xlarge
  - m6id.4xlarge
  - m6id.8xlarge
  - m6id.12xlarge
  - m6id.16xlarge
  - m6id.24xlarge
  - m6id.32xlarge
  - m6id.metal
  - c5n.large
  - c5n.xlarge
  - c5n.2xlarge
  - c5n.4xlarge
  - c5n.9xlarge
  - c5n.18xlarge
  - c5n.metal
  - m6in.large
  - m6in.xlarge
  - m6in.2xlarge
  - m6in.4xlarge
  - m6in.8xlarge
  - m6in.12xlarge
  - m6in.16xlarge
  - m6in.24xlarge
  - m6in.32xlarge
  - m6in.metal
  - m6idn.large
  - m6idn.xlarge
  - m6idn.4xlarge
  - m6idn.8xlarge
  - m6idn.12xlarge
  - m6idn.16xlarge
  - m6idn.24xlarge
  - m6idn.32xlarge
  - m6idn.metal
  - c5a.large
  - c5a.xlarge
  - c5a.2xlarge
  - c5a.4xlarge
  - c5a.8xlarge
  - c5a.12xlarge
  - c5a.16xlarge
  - c5a.24xlarge
  - c5ad.large
  - c5ad.xlarge
  - c5ad.2xlarge
  - c5ad.4xlarge
  - c5ad.8xlarge
  - c5ad.12xlarge
  - c5ad.16xlarge
  - c5ad.24xlarge
  - t3.nano
  - t3.micro
  - t3.small
  - t3.medium
  - t3.large
  - t3.xlarge
  - t3.2xlarge
  - m5.large
  - m5.xlarge
  - m5.2xlarge
  - m5.4xlarge
  - m5.8xlarge
  - m5.12xlarge
  - m5.16xlarge
  - m5.24xlarge
  - m5.metal
  - c6i.large
  - c6i.xlarge
  - c6i.2xlarge
  - c6i.4xlarge
  - c6i.8xlarge
  - c6i.12xlarge
  - c6i.16xlarge
  - c6i.24xlarge
  - c6i.32xlarge
  - c6i.metal
  - c6id.large
  - c6id.xlarge
  - c6id.2xlarge
  - c6id.4xlarge
  - c6id.8xlarge
  - c6id.12xlarge
  - c6id.16xlarge
  - c6id.24xlarge
  - c6id.32xlarge
  - c6id.metal
  - t4g.nano
  - t4g.micro
  - t4g.small
  - t4g.medium
  - t4g.large
  - t4g.xlarge
  - t4g.2xlarge
  - m6g.medium
  - m6g.large
  - m6g.xlarge
  - m6g.2xlarge
  - m6g.4xlarge
  - m6g.8xlarge
  - m6g.12xlarge
  - m6g.16xlarge
  - m6g.metal
  - m6gd.medium
  - m6gd.large
  - m6gd.xlarge
  - m6gd.2xlarge
  - m6gd.4xlarge
  - m6gd.8xlarge
  - m6gd.12xlarge
  - m6gd.16xlarge
  - m6gd.metal
  - c6g.medium
  - c6g.large
  - c6g.xlarge
  - c6g.2xlarge
  - c6g.4xlarge
  - c6g.8xlarge
  - c6g.12xlarge
  - c6g.16xlarge
  - c6g.metal
  - c6gd.medium
  - c6gd.large
  - c6gd.xlarge
  - c6gd.2xlarge
  - c6gd.4xlarge
  - c6gd.8xlarge
  - c6gd.12xlarge
  - c6gd.16xlarge
  - c6gd.metal
  - c7g.medium
  - c7g.large
  - c7g.xlarge
  - c7g.2xlarge
  - c7g.4xlarge
  - c7g.8xlarge
  - c7g.12xlarge
  - c7g.16xlarge
  - c7g.metal
  - m7g.medium
  - m7g.large
  - m7g.xlarge
  - m7g.2xlarge
  - m7g.4xlarge
  - m7g.8xlarge
  - m7g.12xlarge
  - m7g.16xlarge
  - m7g.metal
  - m7i.large
  - m7i.xlarge
  - m7i.2xlarge
  - m7i.4xlarge
  - m7i.8xlarge
  - m7i.12xlarge
  - m7i.16xlarge
  - m7i.24xlarge
  - m7i.48xlarge
  - m7i.metal-24xl
  - m7i.metal-48xl
  - c7i.large
  - c7i.xlarge
  - c7i.2xlarge
  - c7i.4xlarge
